### ISSUE TITLE
Add tab support

### ISSUE THREAD

**Issue by EmilioPeJu** [hir12111/etui#8]
Suggestions:
- The status bar could show the name of the current tab.
- Create_tui_entry and update_tui_entry could have an int parameter for specifying the tab affected.
- Alt+NUMBER could be used to switch to tab NUMBER

**Comment by krmpotic** [comment]
I agree.
We could display name of the current tab by overlaying it on the border.

Also, the current way we display active window we're wasting too much space with borders.
